services:
  db-contract-testing:
    hostname: db.contract_testing.local
    container_name: db.contract_testing.local
    image: postgres:15.4-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '31000:5432'
    volumes:
      - db-contract-testing:/var/lib/postgresql/data
    networks:
      - project-contract-testing-network

  backend-contract-testing:
    hostname: backend.contract_testing.local
    container_name: backend.contract_testing.local
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      db-contract-testing:
        condition: service_healthy
    environment:
      DB_HOST: db.contract_testing.local
      DB_PORT: 5432
      DB_NAME: contract_testing
      JWT_SECRET: 'secreto'
      APP_ENV: staging
    ports:
      - '32000:3000'
    networks:
      - project-contract-testing-network

volumes:
  db-contract-testing:
    driver: local

networks:
  project-contract-testing-network:
    external: true
